displayName=Multi Tagger
author=KeithIsSleeping
description=In multi-combat, highlights untagged NPCs of the type you are fighting so you can tag them too
tags=npc,highlight,multi,combat,slayer,tag
version=
plugins=com.multitagger.MultiTaggerPlugin
build=standard